"""
Excel generation via OpenPyXL — mirrors pdf_export.py but produces .xlsx
bytes for st.download_button.
"""
from io import BytesIO

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter

HEADER_FILL = PatternFill(start_color="0F1420", end_color="0F1420", fill_type="solid")
HEADER_FONT = Font(color="FFFFFF", bold=True)


def _write_table(ws, headers, rows, start_row=1):
    for c, h in enumerate(headers, start=1):
        cell = ws.cell(row=start_row, column=c, value=h)
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.alignment = Alignment(horizontal="center")
    for r, row in enumerate(rows, start=start_row + 1):
        for c, val in enumerate(row, start=1):
            ws.cell(row=r, column=c, value=val)
    for c in range(1, len(headers) + 1):
        ws.column_dimensions[get_column_letter(c)].width = 20


def generate_boq_excel(project, materials) -> bytes:
    wb = Workbook()
    ws = wb.active
    ws.title = "BOQ"

    ws.cell(row=1, column=1, value=f"Bill of Quantities — {project.name} ({project.project_code})").font = Font(bold=True, size=13)
    ws.merge_cells("A1:F1")

    headers = ["Material", "Category", "Unit", "Est. Qty", "Unit Cost (INR)", "Total Cost (INR)"]
    rows = [
        [m.material_name, m.category, m.unit, m.estimated_qty, m.unit_cost, m.total_cost]
        for m in materials
    ]
    grand_total = sum(m.total_cost for m in materials)
    rows.append(["", "", "", "", "Grand Total", grand_total])

    _write_table(ws, headers, rows, start_row=3)

    buf = BytesIO()
    wb.save(buf)
    return buf.getvalue()


def generate_report_excel(sheets: dict, narrative: str = None) -> bytes:
    """sheets: dict[str, (headers, rows)]
    narrative: optional free-text summary (e.g. AI-generated), written to its own sheet with
    wrapped text rather than squeezed into a table cell."""
    wb = Workbook()
    first = True

    if narrative:
        ws = wb.active
        ws.title = "AI Narrative"
        ws.cell(row=1, column=1, value="AI Narrative").font = Font(bold=True, size=13)
        cell = ws.cell(row=3, column=1, value=narrative)
        cell.alignment = Alignment(wrap_text=True, vertical="top")
        ws.merge_cells("A3:F12")
        ws.column_dimensions["A"].width = 100
        note = ws.cell(row=14, column=1, value="Generated by a local AI model — verify against the other sheets.")
        note.font = Font(italic=True, size=9, color="808080")
        first = False

    for name, (headers, rows) in sheets.items():
        ws = wb.active if first else wb.create_sheet()
        ws.title = name[:31]
        _write_table(ws, headers, rows, start_row=1)
        first = False
    buf = BytesIO()
    wb.save(buf)
    return buf.getvalue()
