"""
PDF generation via ReportLab — Bill of Quantities and project/report exports.
Every function returns raw PDF bytes so callers can feed them straight into
st.download_button without touching the filesystem.
"""
from io import BytesIO
from datetime import date

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

NAVY = colors.HexColor("#0F1420")
BLUE = colors.HexColor("#2563EB")
GREY = colors.HexColor("#5B6784")


def _styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="CIHTitle", fontSize=18, leading=22, textColor=NAVY, spaceAfter=4, fontName="Helvetica-Bold"))
    styles.add(ParagraphStyle(name="CIHSubtitle", fontSize=10, textColor=GREY, spaceAfter=14))
    styles.add(ParagraphStyle(name="CIHSection", fontSize=12, textColor=BLUE, spaceBefore=14, spaceAfter=6, fontName="Helvetica-Bold"))
    return styles


def _header_table(rows):
    t = Table(rows, colWidths=[45 * mm, 55 * mm, 45 * mm, 45 * mm])
    t.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (-1, -1), GREY),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    return t


def generate_boq_pdf(project, materials) -> bytes:
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=18 * mm, bottomMargin=18 * mm)
    styles = _styles()
    elements = []

    elements.append(Paragraph("Bill of Quantities", styles["CIHTitle"]))
    elements.append(Paragraph(f"{project.name} &nbsp;·&nbsp; {project.project_code}", styles["CIHSubtitle"]))
    elements.append(_header_table([
        ["Client", project.client_name or "-", "Location", project.location or "-"],
        ["Building Type", project.building_type or "-", "Generated", date.today().isoformat()],
    ]))
    elements.append(Spacer(1, 10))

    data = [["Material", "Category", "Unit", "Est. Qty", "Unit Cost (₹)", "Total Cost (₹)"]]
    grand_total = 0
    for m in materials:
        data.append([
            m.material_name, m.category, m.unit,
            f"{m.estimated_qty:,.1f}", f"{m.unit_cost:,.2f}", f"{m.total_cost:,.2f}",
        ])
        grand_total += m.total_cost
    data.append(["", "", "", "", "Grand Total", f"₹{grand_total:,.2f}"])

    table = Table(data, colWidths=[32 * mm, 26 * mm, 18 * mm, 24 * mm, 30 * mm, 32 * mm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ALIGN", (3, 0), (-1, -1), "RIGHT"),
        ("GRID", (0, 0), (-1, -2), 0.5, colors.HexColor("#D8DCE6")),
        ("LINEABOVE", (0, -1), (-1, -1), 1, NAVY),
        ("FONTNAME", (4, -1), (-1, -1), "Helvetica-Bold"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -2), [colors.white, colors.HexColor("#F4F6FA")]),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    elements.append(table)

    doc.build(elements)
    return buf.getvalue()


def generate_project_report_pdf(project, sections: dict, narrative: str = None) -> bytes:
    """sections: dict[str, list[list[str]]] -> section title -> table rows (first row = header).
    narrative: optional free-text paragraph (e.g. an AI-generated summary) rendered above the
    tables, properly word-wrapped rather than jammed into a table cell."""
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=18 * mm, bottomMargin=18 * mm)
    styles = _styles()
    elements = [
        Paragraph("Project Report", styles["CIHTitle"]),
        Paragraph(f"{project.name} &nbsp;·&nbsp; {project.project_code} &nbsp;·&nbsp; Generated {date.today().isoformat()}", styles["CIHSubtitle"]),
    ]

    if narrative:
        elements.append(Paragraph("AI Narrative", styles["CIHSection"]))
        body_style = ParagraphStyle(name="CIHBody", fontSize=9.5, leading=14, textColor=NAVY)
        elements.append(Paragraph(narrative, body_style))
        elements.append(Paragraph(
            "Generated by a local AI model from the figures in this report — verify against the tables below.",
            ParagraphStyle(name="CIHNote", fontSize=7.5, leading=10, textColor=GREY),
        ))
        elements.append(Spacer(1, 6))

    for title, rows in sections.items():
        elements.append(Paragraph(title, styles["CIHSection"]))
        if not rows or len(rows) < 2:
            elements.append(Paragraph("No data available.", styles["Normal"]))
            continue
        col_count = len(rows[0])
        col_width = (170 * mm) / col_count
        table = Table(rows, colWidths=[col_width] * col_count)
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#EEF2FB")),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8.5),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#D8DCE6")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8F9FC")]),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        elements.append(table)
        elements.append(Spacer(1, 8))

    doc.build(elements)
    return buf.getvalue()
